######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=true distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=103.984 back=-104.301 frontsurface=103.984 backsurface=-104.301 leftsurface=-104.127 rightsurface=104.158 leftslopesurface=0 rightslopesurface=0 frontselect=103.984 backselect=-104.301 boxoffset=0 objects=all
