######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=true distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=120.694 back=-120.812 frontsurface=120.694 backsurface=-120.812 leftsurface=-108.39 rightsurface=133.116 leftslopesurface=0 rightslopesurface=0 frontselect=120.694 backselect=-120.812 boxoffset=0 objects=all
