######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=true distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=105.65 back=-99.4581 frontsurface=105.65 backsurface=-99.4581 leftsurface=-102.508 rightsurface=102.6 leftslopesurface=0 rightslopesurface=0 frontselect=105.65 backselect=-99.4581 boxoffset=0 objects=all
