######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
clip front=10 back=-10 frontsurface=10 backsurface=-10 leftsurface=-10 rightsurface=10 leftslopesurface=0 rightslopesurface=0 frontselect=10 backselect=-10 boxoffset=0 objects=all
