######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=true distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=165.728 back=10.045 frontsurface=165.728 backsurface=10.045 leftsurface=-28.7955 rightsurface=126.887 leftslopesurface=0 rightslopesurface=0 frontselect=165.728 backselect=10.045 boxoffset=0 objects=all
