######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=true distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=176.736 back=-108.948 frontsurface=176.736 backsurface=-108.948 leftsurface=-134.159 rightsurface=151.525 leftslopesurface=0 rightslopesurface=0 frontselect=176.736 backselect=-108.948 boxoffset=0 objects=all
